# Generated by Django 3.2 on 2021-05-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackpot', '0002_auto_20210505_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jackpot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
